Fix compatibility issue with modules that have google/traceur-compiler as a dependency
[traceur-compiler](https://github.com/google/traceur-compiler) adds a polyfill for `Object.defineProperty`, which breaks `cli-color` by causing the color functions on the `clc` object to be `undefined`.

Example:

```
TypeError: Property 'green' of object function (/*…msg*/) {
		var data = fn._cliColorData, close = '';
		return reduce(data, function (str, mod) {
			close = '\x1b[' + mod[1] + 'm' + close;
			return str + '\x1b[' + mod[0] + 'm';
		}, '', true) + join.call(arguments, ' ') + close;
	} is not a function
```

It appears that the polyfill doesn't properly return the object. This commit rearranges `cli-color`'s use of `Object.defineProperty` slightly in order to fix this rather unfortunate compatibility issue.